/// DO NOT EDIT THIS FILE. IT CONTAINS THE TYPES THAT MATCH WITH THE INAPP SDK's Web Script Environment.
/// Prefer editing the website.d.ts file instead.

declare global {
  interface Window {
    reclaimInterceptor: {
      /**
       * Add response middleware when using hawkeye
       *
       * @param middleware
       * @param middlewareName Use a non empty string that is not equal to `'null'`.
       * @returns
       */
      addResponseMiddleware: (
        middleware: (response: any, request: any) => Promise<any>,
        middlewareName?: string
      ) => void;
    };

    /**
     * The Reclaim SDK object to interact with the inapp sdk.
     * Ensure this object is available before using any methods or properties.
     */
    Reclaim: {
      version: 1;
      /**
       * The provider configuration used in this verification session
       */
      provider: ReclaimHttpProvider;
      /**
       * The parameters used when starting verification session with the sdk
       */
      parameters: Record<string, string>;
      /**
       * Start a claim creation with the attestor by sending this request to the inapp sdk.
       */
      requestClaim: (
        claim: HttpClaimRequest
      ) => Promise<ClaimRequestIdentifier | null>;
      /**
       * Returns a list of all claims that have been created in the current verification session.
       */
      getVerificationStatus: () => Promise<VerificationStatus>;
      /**
       * Notify the inapp sdk that the current page requires user interaction, i.e for logging in, etc.
       * Causes the inapp sdk to display this web page to the user and lets them interact with it.
       */
      requiresUserInteraction: (isUserInteractionRequired: boolean) => void;
      /**
       * When true, notifies the inapp sdk to wait for more claims to be created, using `requestClaim`.
       * Doesn't let the inapp sdk to show that the verification has completed.
       *
       * When false, notifies the inapp sdk to not wait for any more claims from js scripts.
       * If proof generation is complete, the inapp sdk will show that the verification has completed.
       */
      canExpectManyClaims: (canExpectManyClaims: boolean) => void;
      /**
       * Add any extra data in the verification response.
       * This data will not go through the claim creation process in the attestor.
       *
       * Note: The root level keys in the data object will be displayed to user. Choose a short and meaningful name for these keys.
       * For example: `{ "User Information": { "name": "John Doe", "email": "john.doe@example.com" } }`
       *
       * Passing string in updatePublicData is supported but not recommended.
       */
      updatePublicData: (data: Record<string, any> | string) => void;
      /**
       * Stop verification and reject any further claims from being created.
       * This is useful when the provider wants to stop the verification process, e.g. when requirements for verification cannot for the user.
       * The `message` provided in the error will be shown to the user.
       *
       * This will also update the verification status and stop backend sdk from listening to any more updates.
       */
      reportProviderError: (
        error: { message: string; [key: string]: any } | string
      ) => void;
      /**
       * Update the default error message that will be shown to the user when the verification fails.
       */
      updateDefaultErrorMessage: (errorMessage: string) => void;
    };
  }

  export interface VerificationStatus {
    isCompleted: boolean;
    error: ReclaimClaimCreationException | null;
    claims: ClaimInformation[];
  }

  export interface ClaimInformation {
    id: ClaimRequestIdentifier;
    request: HttpClaimRequest;
    error: ReclaimClaimCreationException | null;
    isPending: boolean;
  }

  export interface ReclaimHttpProvider {
    name: string | null;
    description: string | null;
    loginUrl: string | null;
    userAgent: UserAgentSettings;
    geoLocation: string | null;
    additionalClientOptions: ReclaimAttestorClientOptions | null;
    useIncognitoWebview: boolean | null;
    requestData: HttpProviderRequest[];
  }

  export type ReclaimAttestorSupportedProtocolVersion = "TLS1_2" | "TLS1_3";

  export interface ReclaimAttestorClientOptions {
    supportedProtocolVersions: ReclaimAttestorSupportedProtocolVersion[];
  }

  export interface UserAgentSettings {
    android: string | null;
    ios: string | null;
  }

  export type UrlType = "REGEX" | "CONSTANT" | "TEMPLATE";

  export type RequestMethodType = "GET" | "POST";

  export type WebCredentialsType = "include" | "same-origin" | "omit";

  export interface HttpProviderRequest {
    url: string | null;
    /**
     * If not provided, defaults to 'TEMPLATE' if url includes `{{` and 'CONSTANT' otherwise
     */
    urlType?: UrlType | null;
    /**
     * Defaults to 'GET'
     */
    method: RequestMethodType | null;
    bodySniff?: BodySniff | null;
    /**
     * Must be unique for each request
     */
    requestHash?: string | null;
    expectedPageUrl?: string | null;
    /**
     * Atleast one response match must be provided.
     */
    responseMatches: ResponseMatch[];
    responseRedactions?: ResponseRedaction[];
    geoLocation?: string | null;
    /**
     * If not provided, defaults to 'include'
     */
    credentials?: WebCredentialsType | null;
  }

  export interface HttpClaimRequest extends HttpProviderRequest {
    headers?: Record<string, string> | null;
    requestBody?: string | null;
    /**
     * Parameters that will be used to generate the witness proof.
     * Same as `extractedParams` in the attestor.
     */
    witnessParameters?: Record<string, string> | null;
    /**
     * Parameters that will be used to generate the witness proof.
     * Same as `witnessParameters` in the attestor.
     * @deprecated Use `witnessParameters` instead.
     */
    extractedParams?: Record<string, string> | null;
  }

  export interface BodySniff {
    /**
     * Defaults to false
     */
    enabled: boolean | null;
    /**
     * The template used for matching and extracting params from `requestBody`.
     * Used when `enabled` is true.
     */
    template: string | null;
  }

  export type ResponseMatchType = "contains" | "regex";

  export interface ResponseMatch {
    /**
     * The value to match against. This can be a string when `type` is `contains` or a regex expression string when `type` is `regex`.
     * If not provided, the response body will be used.
     */
    value?: string | null;
    /**
     * Defaults to 'contains'
     * Decides whether to use `contains` or `regex` strategy for matching response using `value`.
     */
    type?: ResponseMatchType | null;
    /**
     * Defaults to false
     * If true, the response will be matched against the `value` or `regex` expression.
     */
    invert?: boolean | null;
    order?: number | null;
    /**
     * Defaults to false. Atleast one response match must be provided with `isOptional` set to false.
     */
    isOptional?: boolean | null;
  }

  export type ResponseRedactionMatchType = "greedy" | "lazy";

  export interface ResponseRedaction {
    xPath?: string | null;
    jsonPath?: string | null;
    regex?: string | null;
    /**
     * Decides whether to use `(.*)` aka greedy matching for variable values or use `(.*?)` aka lazy matching.
     * When null, defaults to 'greedy' if parameter name is suffixed with `_GRD` and 'lazy' otherwise.
     */
    matchType?: ResponseRedactionMatchType | null;
    hash?: string | null;
  }

  export type ClaimRequestIdentifier = string;

  export interface ReclaimClaimCreationException {
    message: string;
  }
}

export {};
